template<int B = 64>
struct Basis {
    static_assert(1 <= B && B <= 64);
    using T = std::conditional_t<(B <= 32), std::uint32_t, std::uint64_t>;
    std::array<T, B> d{};

    void clear() { d.fill(0); }

    // Returns whether the rank increased. x must be in [0, 2^B).
    bool insert(T x) {
        if constexpr (B < 64) assert((std::uint64_t(x) >> B) == 0);
        while (x) {
            int i = 63 - __builtin_clzll(x);
            if (!d[i]) {
                d[i] = x;
                return true;
            }
            x ^= d[i];
        }
        return false;
    }

    T querymax(T x = 0) const {
        for (int i = B - 1; i >= 0; --i)
            x = std::max(x, T(x ^ d[i]));
        return x;
    }

    T querymin(T x = 0) const {
        for (int i = B - 1; i >= 0; --i)
            x = std::min(x, T(x ^ d[i]));
        return x;
    }

    bool contains(T x) const { return querymin(x) == 0; }

    // ===== OPTIONAL: dimension, merge, smallest nonzero =====
    int rank() const {
        int r = 0;
        for (T x : d) r += (x != 0);
        return r;
    }

    Basis& operator+=(const Basis& b) {
        for (T x : b.d)
            if (x) insert(x);
        return *this;
    }

    friend Basis operator+(Basis a, const Basis& b) { return a += b; }

    T min_nonzero() const {
        for (T x : d)
            if (x) return x;
        return 0; // no nonzero value exists
    }

    // ===== OPTIONAL: kth DISTINCT value in {x XOR s : s in span} =====
    // Zero-based: kth(0) is the smallest, empty subset is included.
    // nullopt means invalid k. Supports rank=64 without shifting by 64.
    std::optional<T> kth(std::uint64_t k, T x = 0) const {
        int r = rank();
        if (r < 64 && (k >> r)) return std::nullopt;
        for (int i = B - 1; i >= 0; --i) {
            if (!d[i]) continue;
            --r;
            if (((x >> i) & 1) != ((k >> r) & 1))
                x ^= d[i];
        }
        return x;
    }
};

// ===== pos_basis.hpp =====

// Keeps one weighted/position-tagged basis. It does not retain past snapshots.
// Typical usage: insert a[i] with position i in increasing order.
template<int B = 64>
struct PosBasis {
    using T = typename Basis<B>::T;
    Basis<B> b;
    std::array<int, B> pos{};

    void clear() { b.clear(); pos.fill(0); }

    void insert(T x, int p) {
        assert(p > 0);
        if constexpr (B < 64) assert((std::uint64_t(x) >> B) == 0);
        while (x) {
            int i = 63 - __builtin_clzll(x);
            if (!b.d[i]) {
                b.d[i] = x;
                pos[i] = p;
                return;
            }
            if (pos[i] < p) {
                std::swap(pos[i], p);
                std::swap(b.d[i], x);
            }
            x ^= b.d[i];
        }
    }

    // The subspace generated by inserted elements whose positions are >= l.
    // Existing pivots remain distinct; direct copying costs O(B), not O(B^2).
    Basis<B> query(int l) const {
        assert(l >= 1);
        Basis<B> ans;
        for (int i = 0; i < B; ++i)
            if (pos[i] >= l) ans.d[i] = b.d[i];
        return ans;
    }

    // ===== OPTIONAL fast path: no temporary Basis =====
    T querymax(int l, T x = 0) const {
        assert(l >= 1);
        for (int i = B - 1; i >= 0; --i)
            if (pos[i] >= l) x = std::max(x, T(x ^ b.d[i]));
        return x;
    }
};

// ===== range_basis.hpp =====
#include <limits>
#include <vector>

// 1-based [l,r]. A static array / tail-appends only; no arbitrary point edits.
template<int B = 64>
struct RangeBasis {
    using T = typename Basis<B>::T;
    std::vector<PosBasis<B>> pre{PosBasis<B>{}};

    RangeBasis() = default;
    template<class U>
    RangeBasis(const std::vector<U>& a) { init(a); }

    int size() const { return int(pre.size()) - 1; }

    template<class U>
    void init(const std::vector<U>& a) {
        assert(a.size() <= std::size_t(std::numeric_limits<int>::max()));
        int n = std::max(0, int(a.size()) - 1);
        pre.resize(n + 1);
        pre[0] = PosBasis<B>{};
        for (int i = 1; i <= n; ++i) {
            pre[i] = pre[i - 1];
            pre[i].insert(T(a[i]), i);
        }
    }

    Basis<B> query(int l, int r) const {
        if (l > r) return {};
        assert(1 <= l && r <= size());
        return pre[r].query(l);
    }

    // ===== OPTIONAL fast path =====
    T querymax(int l, int r, T x = 0) const {
        if (l > r) return x;
        assert(1 <= l && r <= size());
        return pre[r].querymax(l, x);
    }

    // ===== OPTIONAL: append / undo last append =====
    void append(T x) {
        assert(pre.size() < std::size_t(std::numeric_limits<int>::max()));
        int p = int(pre.size());
        pre.push_back(pre.back());
        pre.back().insert(x, p);
    }

    void pop_back() {
        assert(size() > 0);
        pre.pop_back();
    }
};
